package lsys

type LFractal struct {
	Name    string            // identifier
	Axiom   string            // beginning string
	Rules   map[string]string // rewrite rules
	Levels  int               // rewrite generations
	Theta   float64           // starting angle (orientation)
	Angle   float64           // turn angle
	OnePath bool              // force drawing the entire fractal in a single path
}

var fractals = []LFractal{
	{
		Name:    "Tree1",
		Axiom:   "B",
		Rules:   map[string]string{"B": "F[-B]+B", "F": "FF"},
		Levels:  8,
		Theta:   90.0,
		Angle:   20.0,
		OnePath: false,
	},
	{
		Name:    "Tree2",
		Axiom:   "F",
		Rules:   map[string]string{"F": "FF+[+F-F-F]-[-F+F+F]"},
		Levels:  4,
		Theta:   90.0,
		Angle:   25.0,
		OnePath: false,
	},
	{
		Name:    "Tree3",
		Axiom:   "VZFFF",
		Rules:   map[string]string{"V": "[+++W][---W]YV", "W": "+X[-W]Z", "X": "-W[+X]Z", "Y": "YZ", "Z": "[-FFF][+FFF]F", "F": "F"},
		Levels:  11,
		Theta:   90.0,
		Angle:   18.0,
		OnePath: false,
	},
	{
		Name:    "Flower1",
		Axiom:   "F",
		Rules:   map[string]string{"F": "F[+F]F[-F]F"},
		Levels:  5,
		Theta:   90.0,
		Angle:   25.7,
		OnePath: false,
	},
	{
		Name:    "Bush",
		Axiom:   "X",
		Rules:   map[string]string{"X": "F-[[X]+X]+F[+FX]-X", "F": "FF"},
		Levels:  7,
		Theta:   90.0,
		Angle:   22.5,
		OnePath: false,
	},
	{
		Name:    "Hilbert",
		Axiom:   "X",
		Rules:   map[string]string{"X": "-YF+XFX+FY-", "Y": "+XF-YFY-FX+", "F": "F"},
		Levels:  6,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Koch",
		Axiom:   "F++F++F",
		Rules:   map[string]string{"F": "F-F++F-F"},
		Levels:  4,
		Theta:   0.0,
		Angle:   60.0,
		OnePath: false,
	},
	{
		Name:    "Koch2",
		Axiom:   "F",
		Rules:   map[string]string{"F": "F+F-F-F+F"},
		Levels:  7,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Koch3",
		Axiom:   "F",
		Rules:   map[string]string{"F": "F+F-F-F+F"},
		Levels:  7,
		Theta:   0.0,
		Angle:   85.0,
		OnePath: false,
	},
	{
		Name:    "KochIsland",
		Axiom:   "F+F+F+F",
		Rules:   map[string]string{"F": "F+F-F-FF+F+F-F"},
		Levels:  4,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "KochStar",
		Axiom:   "X+X+X+X+X+X+X+X",
		Rules:   map[string]string{"X": "X+YF++YF-FX--FXFX-YF+X", "Y": "-FX+YFYF++YF+FX--FX-YF", "F": "F"},
		Levels:  4,
		Theta:   0.0,
		Angle:   45.0,
		OnePath: false,
	},
	{
		Name:    "Sierpinski",
		Axiom:   "F--F--F",
		Rules:   map[string]string{"F": "F--F--F--ff", "f": "ff"},
		Levels:  7,
		Theta:   0.0,
		Angle:   60.0,
		OnePath: false,
	},
	{
		Name:    "Sierpenski2",
		Axiom:   "F+F+F+F",
		Rules:   map[string]string{"F": "FF+F+F+F+FF"},
		Levels:  5,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Sierpenski3",
		Axiom:   "YF",
		Rules:   map[string]string{"X": "YF+XF+Y", "Y": "XF-YF-X", "F": "F"},
		Levels:  7,
		Theta:   0.0,
		Angle:   60.0,
		OnePath: false,
	},
	{
		Name:    "Sierpenski4",
		Axiom:   "F+XF+F+XF",
		Rules:   map[string]string{"X": "XF-F+F-XF+F+XF-F+F-X", "F": "F"},
		Levels:  5,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Dragon",
		Axiom:   "FX",
		Rules:   map[string]string{"X": "X+YF+", "Y": "-FX-Y", "F": "F"},
		Levels:  12,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Peano",
		Axiom:   "X",
		Rules:   map[string]string{"X": "XFYFX+F+YFXFY-F-XFYFX", "Y": "YFXFY-F-XFYFX+F+YFXFY", "F": "F"},
		Levels:  4,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Gosper",
		Axiom:   "XF",
		Rules:   map[string]string{"X": "X+YF++YF-FX--FXFX-YF+", "Y": "-FX+YFYF++YF+FX--FX-Y", "F": "F"},
		Levels:  4,
		Theta:   0.0,
		Angle:   60.0,
		OnePath: false,
	},
	{
		Name:    "QuadraticGosper",
		Axiom:   "-YF",
		Rules:   map[string]string{"X": "XFX-YF-YF+FX+FX-YF-YFFX+YF+FXFXYF-FX+YF+FXFX+YF-FXYF-YF-FX+FX+YFYF-", "Y": "+FXFX-YF-YF+FX+FXYF+FX-YFYF-FX-YF+FXYFYF-FX-YFFX+FX+YF-YF-FX+FX+YFY", "F": "F"},
		Levels:  2,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Snow1",
		Axiom:   "F++F++F++F++F",
		Rules:   map[string]string{"F": "F++F++F-----F-F++F"},
		Levels:  4,
		Theta:   0.0,
		Angle:   36.0,
		OnePath: false,
	},
	{
		Name:    "Snow2",
		Axiom:   "F----F----F----F----F",
		Rules:   map[string]string{"F": "F----F----F----------F++F----F"},
		Levels:  4,
		Theta:   0.0,
		Angle:   18.0,
		OnePath: false,
	},
	{
		Name:    "Penrose",
		Axiom:   "[X]++[X]++[X]++[X]++[X]",
		Rules:   map[string]string{"W": "YF++ZF----XF[-YF----WF]++", "X": "+YF--ZF[---WF--XF]+", "Y": "-WF++XF[+++YF++ZF]-", "Z": "--YF++++WF[+ZF++++XF]--XF", "F": ""},
		Levels:  5,
		Theta:   0.0,
		Angle:   36.0,
		OnePath: false,
	},
	{
		Name:    "Trucks",
		Axiom:   "F-F-F-F",
		Rules:   map[string]string{"F": "F-f+FF-F-FF-Ff-FF+f-FF+F+FF+Ff+FFF", "f": "ffffff"},
		Levels:  3,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Stars",
		Axiom:   "F+F+F+F",
		Rules:   map[string]string{"F": "FF+F+F+F+F+F-F"},
		Levels:  5,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Maze",
		Axiom:   "F+F+F+F",
		Rules:   map[string]string{"F": "FF+F-F+F+FF"},
		Levels:  4,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Frost",
		Axiom:   "F+F+F+F",
		Rules:   map[string]string{"F": "FF+F++F+F"},
		Levels:  5,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: false,
	},
	{
		Name:    "Hexagon",
		Axiom:   "X",
		Rules:   map[string]string{"X": "[-F+F[Y]+F][+F-F[X]-F]", "Y": "[-F+F[Y]+F][+F-F-F]", "F": "F"},
		Levels:  10,
		Theta:   0.0,
		Angle:   60.0,
		OnePath: false,
	},
	{
		Name:    "Mango",
		Axiom:   "A---A",
		Rules:   map[string]string{"A": "f-F+Z+F-fA", "Z": "F-FF-F--[--Z]F-FF-F--F-FF-F--", "F": "F", "f": "f"},
		Levels:  10,
		Theta:   0.0,
		Angle:   60.0,
		OnePath: false,
	},
	{
		Name:    "Triangle",
		Axiom:   "F+F+F",
		Rules:   map[string]string{"F": "F-F+F"},
		Levels:  5,
		Theta:   0.0,
		Angle:   120.0,
		OnePath: false,
	},
	{
		Name:    "Shield",
		Axiom:   "AAAA",
		Rules:   map[string]string{"A": "X+X+X+X+X+X+", "X": "[F+F+F+F[---X-Y]+++++F++++++++F-F-F-F]", "Y": "[F+F+F+F[---Y]+++++F++++++++F-F-F-F]", "F": "F"},
		Levels:  11,
		Theta:   0.0,
		Angle:   15.0,
		OnePath: true,
	},
	{
		Name:    "Corner",
		Axiom:   "W",
		Rules:   map[string]string{"W": "+++X--F--ZFX+", "X": "---W++F++YFW-", "Y": "+ZFX--F--Z+++", "Z": "-YFW++F++Y---", "F": "F"},
		Levels:  6,
		Theta:   0.0,
		Angle:   30.0,
		OnePath: true,
	},
	{
		Name:    "Border",
		Axiom:   "XYXYXYX+XYXYXYX+XYXYXYX+XYXYXYX",
		Rules:   map[string]string{"X": "FX+FX+FXFY-FY-", "Y": "+FX+FXFY-FY-FY", "F": ""},
		Levels:  2,
		Theta:   0.0,
		Angle:   90.0,
		OnePath: true,
	},
}
